### PR TITLE
update trigger

### PR DESCRIPTION
**Pull request by pietrangelo**

### CODE REVIEW

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **w-caffiero-entando**

If they are not already assigned, you can assign the PR to them by writing `/assign @w-caffiero-entando` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando-k8s%2Fentando-k8s-operator-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando-k8s/entando-k8s-operator-common/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Review by user-54dbb57a — APPROVED** [review]

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando-k8s/entando-k8s-operator-common/pull/65#pullrequestreview-801457729" title="Approved">w-caffiero-entando</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando-k8s%2Fentando-k8s-operator-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando-k8s/entando-k8s-operator-common/blob/master/OWNERS)~~ [w-caffiero-entando]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Comment by entando-jx** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to merge repository config with repository entando-k8s/entando-k8s-operator-common for ref 1ed6898641b1c7ca95234b9809758f305b5db7fc
* failed to initialize config
* could not set regex
* for job pr, rerun command "/retest" does not match trigger "/test pr"

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando-k8s/entando-k8s-operator-common/pull/65#pullrequestreview-801457729" title="Approved">w-caffiero-entando</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando-k8s%2Fentando-k8s-operator-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by entando-jx** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[w-caffiero-entando](https://github.com/entando-k8s/entando-k8s-operator-common/pull/65#pullrequestreview-801457729 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=entando-k8s%2Fentando-k8s-operator-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:


Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by entando-jx** [comment]
@pietrangelo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 76951178a67c50bd4a82fb6e60b159a71eca4b36 | [link](http://dashboard-jx.jx.entando.io/namespaces/jx/pipelineruns/ndo-k8s-operator-common-pr-65-pr-p6v4f) | `/test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by entando-jx** [comment]
@pietrangelo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 76951178a67c50bd4a82fb6e60b159a71eca4b36 | [link](http://dashboard-jx.jx.entando.io/namespaces/jx/pipelineruns/ndo-k8s-operator-common-pr-65-pr-p6v4f) | `/test`
pr-build | 1ed6898641b1c7ca95234b9809758f305b5db7fc | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by entando-jx** [comment]
@pietrangelo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 76951178a67c50bd4a82fb6e60b159a71eca4b36 | [link](http://dashboard-jx.jx.entando.io/namespaces/jx/pipelineruns/ndo-k8s-operator-common-pr-65-pr-p6v4f) | `/test`
pr-build | 76951178a67c50bd4a82fb6e60b159a71eca4b36 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by user-54dbb57a** [comment]
due to the complexity we decided to not migrate to jx3, closing

**Pull request closed without merging**
